name: Sync Automático de Componentes

on:
  schedule:
    - cron: '0 * * * *'  # Executa a cada hora (ajusta como quiseres)

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório principal
        uses: actions/checkout@v3
        
      - name: Configurar chaves SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Executar script de sincronização
        run: |
          # Diretório temporário para clonar os repositórios
          SYNC_DIR="/tmp/storybook-sync"

          # Lista de repositórios dos colaboradores
          REPOS=(
              "git@github.com:andremadu/colaborador1-components.git"
              "git@github.com:andremadu/colaborador2-components.git"
          )

          # Apagar diretório antigo e recriá-lo
          rm -rf $SYNC_DIR
          mkdir -p $SYNC_DIR

          # Loop por cada repositório e copiar ficheiros
          for REPO in "${REPOS[@]}"; do
              REPO_NAME=$(basename $REPO .git)
              git clone $REPO $SYNC_DIR/$REPO_NAME
              cp -r $SYNC_DIR/$REPO_NAME/componentes/* ./componentes/
          done

      - name: Commit e Push das alterações
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync automático de componentes" || echo "Nenhuma mudança para commitar"
          git push origin main
