name: Sync Components

on:
  schedule:
    - cron: '0 * * * *'  # Corre a cada hora
  workflow_dispatch:  # Permite execução manual

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório central
        uses: actions/checkout@v4

      - name: Configurar SSH para acesso ao GitHub
        run: |
          mkdir -p ~/.ssh
          
          # Criar ficheiro de chave SSH 1
          echo "${{ secrets.SSH_PRIVATE_KEY1 }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Criar ficheiro de chave SSH 2 (caso seja necessária)
          echo "${{ secrets.SSH_PRIVATE_KEY2 }}" | tr -d '\r' > ~/.ssh/id_rsa_2
          chmod 600 ~/.ssh/id_rsa_2

          # Adicionar GitHub aos hosts conhecidos
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          # Criar ficheiro de configuração SSH para garantir que ambas as chaves são usadas
          echo -e "Host github.com\n\tIdentityFile ~/.ssh/id_rsa\n\tIdentityFile ~/.ssh/id_rsa_2\n\tStrictHostKeyChecking no" > ~/.ssh/config

          # Configurar Git
          git config --global user.email "andremm2412@gmail.com"
          git config --global user.name "andremadu"
          git config --global core.sshCommand "ssh -F ~/.ssh/config"

      - name: Verificar acesso SSH
        run: ssh -T git@github.com || true

      - name: Executar script de sincronização
        run: |
          chmod +x sync.sh
          ./sync.sh

      - name: Commit e push das alterações
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "Sem alterações para commit."
          else
            git commit -m "Sync automático de componentes"
            git push origin main
          fi
