name: Sync Components

on:
  schedule:
    - cron: '0 * * * *'  # Corre a cada hora
  workflow_dispatch:  # Permite execução manual

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório central
        uses: actions/checkout@v4

      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          
          # Adicionar as duas chaves SSH
          echo "${{ secrets.SSH_PRIVATE_KEY1 }}" | tr -d '\r' > ~/.ssh/storybook1
          echo "${{ secrets.SSH_PRIVATE_KEY2 }}" | tr -d '\r' > ~/.ssh/storybook2
          
          chmod 600 ~/.ssh/storybook1 ~/.ssh/storybook2
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/storybook1
          ssh-add ~/.ssh/storybook2
          
          export GIT_SSH_COMMAND='ssh -i ~/.ssh/storybook1 -o StrictHostKeyChecking=no'

      - name: Configurar identidade do Git
        run: |
          git config --global user.email "andremm2412@gmail.com"
          git config --global user.name "andremadu"

      - name: Executar sync.sh
        run: |
          chmod +x sync.sh
          ./sync.sh


